/**
 * Single source of truth for the permission catalog.
 * Format: "<module>:<action>". Consumed by the Prisma seed script (to populate the
 * Permission table) and by the backend's requirePermission() RBAC middleware.
 */

const CRUD_MODULES = [
  "users",
  "roles",
  "departments",
  "leads",
  "contacts",
  "companies",
  "deals",
  "tasks",
  "conversations",
  "tickets",
  "calendar",
  "campaigns",
  "workflows",
  "documents",
  "knowledge_base",
] as const;

type CrudModule = (typeof CRUD_MODULES)[number];
type CrudAction = "create" | "read" | "update" | "delete";

type CrudPermissionKey = `${CrudModule}:${CrudAction}`;

const CRUD_PERMISSIONS: CrudPermissionKey[] = CRUD_MODULES.flatMap((module) =>
  (["create", "read", "update", "delete"] as const).map(
    (action): CrudPermissionKey => `${module}:${action}`,
  ),
);

/** Module-specific permissions beyond plain CRUD. */
const EXTRA_PERMISSIONS = [
  "leads:import",
  "leads:export",
  "leads:assign",
  "deals:manage_pipeline",
  "tickets:manage_sla",
  "reports:read",
  "analytics:read",
  "automation:manage",
  "notifications:manage",
  "settings:manage",
  "settings:manage_integrations",
  "audit:read",
  // Employee Presence/Attendance list — deliberately not plain CRUD (attendance rows are
  // system-generated by login/heartbeat/logout, never created or edited by hand).
  "attendance:read",
  // Approve/reject WFH & Leave requests, and view every employee's request history —
  // deliberately excluded from Admin's "everything but settings/audit" grant in
  // apps/api/prisma/seed.ts, so only Super Admin holds it. Submitting/viewing your own
  // requests needs no permission at all (like /auth/me) — every employee can do that.
  "attendance_requests:approve",
  // Irreversibly removing a user account (as opposed to users:delete, which only
  // deactivates) — deliberately excluded from Admin's wildcard grant in prisma/seed.ts,
  // Super Admin only.
  "users:delete_permanent",
  // Viewing every employee's Day Report (submitting/viewing your own needs no permission,
  // like /auth/me and attendance requests) — deliberately excluded from Admin's wildcard
  // grant in apps/api/prisma/seed.ts, so only Super Admin can see everyone's reports.
  "daily_reports:read",
  // RM Requests — a live proxy onto gifftai_official_web's RM Funding Requests (real money,
  // two-admin approve→credit) and RM Manual Requests. `read` views both lists; `manage`
  // covers approve/credit/reject, manual-request status changes, and RM assignment.
  // Deliberately excluded from Admin's wildcard grant in apps/api/prisma/seed.ts, same as
  // audit:read/daily_reports:read above — Super Admin only by default since this surfaces
  // real fund movement, grantable to other roles later via the Roles UI.
  "rm_requests:read",
  "rm_requests:manage",
  // Hostinger Mail inbox/sent — view every mailbox conversation and send/reply as any of
  // the 8 mailbox addresses. Deliberately split from settings:manage_integrations (which
  // gates connecting/disconnecting the mailbox) so day-to-day mail use doesn't require
  // integration-admin rights, same split as leads:read/leads:update vs
  // settings:manage_integrations for WhatsApp.
  "mail:read",
  "mail:send",
  // Blog / CMS — a live proxy onto gifftai_official_web's admin API `/blog/*` routes
  // (the blog_posts table lives in that repo's Postgres; this repo never persists a post).
  // `read` views the post list/detail + slug check; `manage` covers create/update/publish/
  // unpublish/delete and image upload. Deliberately excluded from Admin's wildcard grant in
  // apps/api/prisma/seed.ts, same convention as rm_requests/audit/tickets above — Super
  // Admin by default, grantable to a marketing-style role via the Roles UI. These CRM
  // permissions are the source of truth: the CRM authenticates to gifftai as a service
  // and asserts the holder's read/manage scope (X-CRM-Blog-Scope), which gifftai enforces
  // — the acting user does NOT need a gifftai admin/employee account. See
  // modules/blog/blogAdminClient.ts.
  "blog:read",
  "blog:manage",
] as const;

export const PERMISSIONS = [...CRUD_PERMISSIONS, ...EXTRA_PERMISSIONS] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const ROLES = {
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
  SALES_MANAGER: "Sales Manager",
  SALES_REP: "Sales Rep",
  SUPPORT_AGENT: "Support Agent",
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];
